version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: wednesday

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
      day: wednesday
